export const sarcasticResponses = [
    "Nice try, but 'bomb casserole' isn't on the menu today.",
    "Sorry, we don't have a recipe for 'illegal surprise'. How about a fruit salad?",
    "Hmm, that doesn't sound very appetizing. Maybe stick to actual food?",
    "I'm pretty sure that's not in any cookbook I've ever seen.",
    "Let's keep it legal and edible, shall we?",
    "That's a creative idea, but perhaps too creative for a kitchen.",
    "I don't think Gordon Ramsay would approve of that one.",
    "Are you trying to cook or start a science experiment?",
    "That sounds more like a crime than a cuisine.",
    "I'm all for culinary adventures, but let's not push it too far.",
    "Ah, going for the 'most wanted' menu, are we?",
    "I think you misunderstood when I said 'explosive flavors'.",
    "That recipe sounds like it belongs in a police report, not a cookbook.",
    "I'm a recipe generator, not a getaway driver.",
    "Sorry, my 'cooking with contraband' cookbook is currently out of stock.",
    "I don't think that's what they meant by 'mind-blowing cuisine'.",
    "Let's aim for 'delicious', not 'dangerous', shall we?",
    "I'm afraid that recipe might be too spicy for the DEA's taste.",
    "That's less 'Masterchef' and more 'Breaking Bad'.",
    "I think you've confused 'bake' with 'baked'.",
    "That recipe sounds like it comes with a side of handcuffs.",
    "I'm not sure if that needs a chef or a HAZMAT team.",
    "Pretty sure that's not what they mean by 'high cuisine'.",
    "Let's stick to ingredients you can buy without a fake ID.",
    "I don't think that pairs well with anything except maybe prison food.",
    "That recipe seems more fit for a chemistry lab than a kitchen.",
    "I'm a recipe app, not a 'get rich quick' scheme generator.",
    "Let's keep our cooking adventures on the right side of the law, okay?",
    "I think you misunderstood when I said we could make some 'dope' dishes.",
    "That's not the kind of 'high-end cuisine' we're going for here."
  ];